# GitPod Workspace image to use
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Upgrade pip and outdated packages 
    init: |
      python -m pip install --upgrade pip
    # Show version
    command: |
      pip --version
      cookiecutter --version
      hub version
      gh version
