# GitPod Workspace image to use
image: gitpod/workspace-full

tasks:
  - name: Upgrade pip and outdated packages 
    init: |
      python -m pip install --upgrade pip
      command -v cookiecutter >/dev/null 2>&1 || {
        pip install --quiet --user cookiecutter || exit 0
      }
      command -v hub >/dev/null 2>&1 || {
        brew install hub || exit 0
      }
