# GitPod Workspace image to use
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Upgrade pip and outdated packages 
    init: |
      python -m pip install --upgrade pip
      HOMEBREW_NO_ENV_HINTS=1 brew install cookiecutter gh hub
    # Show version
    command: |
      pip --version
      brew --version
      cookiecutter --version
      hub --version
      gh --version
